name: GinAdmin
on: [push]
jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."