name: GinAdmin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image  : redis
        ports:
          # Maps tcp port 6379 on service container to the host
          - 6379:6379
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE     : test
          MYSQL_ROOT_PASSWORD: 12345678
        ports:
          # Maps tcp port 3306 on service container to the host
          - 3306:3306

